### ISSUE TITLE
📚 카테고리 페이지

### ISSUE THREAD

**Issue by rlotr02** [Team-Never-Land/ThinkerBell-ios#4]
## 🍀 Summary
카테고리 페이지 전체 구현

## ✔️ Task & Description
- [x] 텍스트&목록의 카테고리 버튼 컴포넌트
- [x] 카테고리 페이지
- [x] 공지 페이지
- [x] 검색창 헤더
- [x] 검색 화면
- [x] 검색 EMPTY 화면
- [x] 즐겨찾기 토스트 메시지
- [x] 카테고리별 방문한 id AsyncStorage에 저장

## ☁️ Reference
- [StatusBar 색상 변경1](https://devbksheen.tistory.com/entry/Android-iOS-StatusBar-%EC%83%89%EC%83%81-%EB%B3%80%EA%B2%BD)
- [StatusBar 색상 변경2](https://devocean.sk.com/blog/techBoardDetail.do?ID=164739)
